### ISSUE TITLE
"breaking:" tag is taking in consideration non master branches

### ISSUE THREAD

**Issue by paulopontesm** [codacy/git-version#11] opened 2019-01-15 10:58 UTC
This results in a jump of 2 major versions when publishing something with a "breaking" commit.

<img width="496" alt="image" src="https://user-images.githubusercontent.com/3610528/51176007-bc5dfe80-18b3-11e9-9e69-0848a79c3463.png">

**Comment by andreaTP** [comment] 2019-01-15 11:16
I think this is a duplicate of #9

**Comment by paulopontesm** [comment] 2019-01-15 11:18
hmm.. strange. I got this this with the latest version.
I'll try to check why this happened later

**Comment by paulopontesm** [comment] 2019-01-15 15:21
Seems to do the same on minors 

![image](https://user-images.githubusercontent.com/3610528/51190061-42407080-18d9-11e9-8d07-59f489b75578.png)

**Closed** 2019-01-16 10:54 UTC
